// Code generated by entc, DO NOT EDIT.

package post

import (
	"time"
)

const (
	// Label holds the string label denoting the post type in the database.
	Label = "post"
	// FieldID holds the string denoting the id field in the database.
	FieldID                  = "id"                   // FieldTitle holds the string denoting the title vertex property in the database.
	FieldTitle               = "title"                // FieldTitleTranslations holds the string denoting the title_translations vertex property in the database.
	FieldTitleTranslations   = "title_translations"   // FieldSubject holds the string denoting the subject vertex property in the database.
	FieldSubject             = "subject"              // FieldSubjectTranslations holds the string denoting the subject_translations vertex property in the database.
	FieldSubjectTranslations = "subject_translations" // FieldURL holds the string denoting the url vertex property in the database.
	FieldURL                 = "url"                  // FieldPublishedAt holds the string denoting the published_at vertex property in the database.
	FieldPublishedAt         = "published_at"         // FieldDescription holds the string denoting the description vertex property in the database.
	FieldDescription         = "description"          // FieldH1 holds the string denoting the h1 vertex property in the database.
	FieldH1                  = "h1"                   // FieldContent holds the string denoting the content vertex property in the database.
	FieldContent             = "content"              // FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt           = "created_at"           // FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt           = "updated_at"           // FieldUpdatedBy holds the string denoting the updated_by vertex property in the database.
	FieldUpdatedBy           = "updated_by"

	// EdgeSource holds the string denoting the source edge name in mutations.
	EdgeSource = "source"

	// Table holds the table name of the post in the database.
	Table = "posts"
	// SourceTable is the table the holds the source relation/edge.
	SourceTable = "posts"
	// SourceInverseTable is the table name for the Source entity.
	// It exists in this package in order to avoid circular dependency with the "source" package.
	SourceInverseTable = "sources"
	// SourceColumn is the table column denoting the source relation/edge.
	SourceColumn = "source_posts"
)

// Columns holds all SQL columns for post fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldTitleTranslations,
	FieldSubject,
	FieldSubjectTranslations,
	FieldURL,
	FieldPublishedAt,
	FieldDescription,
	FieldH1,
	FieldContent,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUpdatedBy,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Post type.
var ForeignKeys = []string{
	"source_posts",
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt func() time.Time
)
