// Code generated by entc, DO NOT EDIT.

package globalsettings

const (
	// Label holds the string label denoting the globalsettings type in the database.
	Label = "globalsettings"
	// FieldID holds the string denoting the id field in the database.
	FieldID             = "id" // FieldClickbaitWords holds the string denoting the clickbait_words vertex property in the database.
	FieldClickbaitWords = "clickbait_words"

	// Table holds the table name of the globalsettings in the database.
	Table = "globalsettings"
)

// Columns holds all SQL columns for globalsettings fields.
var Columns = []string{
	FieldID,
	FieldClickbaitWords,
}
