// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "title_translations", Type: field.TypeJSON},
		{Name: "subject", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "subject_translations", Type: field.TypeJSON},
		{Name: "url", Type: field.TypeString},
		{Name: "published_at", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString},
		{Name: "h1", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt},
		{Name: "source_posts", Type: field.TypeInt, Nullable: true},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "posts_sources_posts",
				Columns: []*schema.Column{PostsColumns[13]},

				RefColumns: []*schema.Column{SourcesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SourcesColumns holds the columns for the "sources" table.
	SourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "language", Type: field.TypeEnum, Enums: []string{"ru", "en"}},
		{Name: "source_children", Type: field.TypeInt, Nullable: true},
	}
	// SourcesTable holds the schema information for the "sources" table.
	SourcesTable = &schema.Table{
		Name:       "sources",
		Columns:    SourcesColumns,
		PrimaryKey: []*schema.Column{SourcesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "sources_sources_children",
				Columns: []*schema.Column{SourcesColumns[4]},

				RefColumns: []*schema.Column{SourcesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "tg_id", Type: field.TypeInt, Unique: true},
		{Name: "payment_info", Type: field.TypeString, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PostsTable,
		SourcesTable,
		UsersTable,
	}
)

func init() {
	PostsTable.ForeignKeys[0].RefTable = SourcesTable
	SourcesTable.ForeignKeys[0].RefTable = SourcesTable
}
