// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/ErrorBoi/feedparserbot/ent/predicate"
	"github.com/ErrorBoi/feedparserbot/ent/user"
	"github.com/ErrorBoi/feedparserbot/ent/usersettings"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// UserSettingsUpdate is the builder for updating UserSettings entities.
type UserSettingsUpdate struct {
	config
	hooks      []Hook
	mutation   *UserSettingsMutation
	predicates []predicate.UserSettings
}

// Where adds a new predicate for the builder.
func (usu *UserSettingsUpdate) Where(ps ...predicate.UserSettings) *UserSettingsUpdate {
	usu.predicates = append(usu.predicates, ps...)
	return usu
}

// SetUrgentWords sets the urgent_words field.
func (usu *UserSettingsUpdate) SetUrgentWords(s []string) *UserSettingsUpdate {
	usu.mutation.SetUrgentWords(s)
	return usu
}

// ClearUrgentWords clears the value of urgent_words.
func (usu *UserSettingsUpdate) ClearUrgentWords() *UserSettingsUpdate {
	usu.mutation.ClearUrgentWords()
	return usu
}

// SetBannedWords sets the banned_words field.
func (usu *UserSettingsUpdate) SetBannedWords(s []string) *UserSettingsUpdate {
	usu.mutation.SetBannedWords(s)
	return usu
}

// ClearBannedWords clears the value of banned_words.
func (usu *UserSettingsUpdate) ClearBannedWords() *UserSettingsUpdate {
	usu.mutation.ClearBannedWords()
	return usu
}

// SetLanguage sets the language field.
func (usu *UserSettingsUpdate) SetLanguage(u usersettings.Language) *UserSettingsUpdate {
	usu.mutation.SetLanguage(u)
	return usu
}

// SetNillableLanguage sets the language field if the given value is not nil.
func (usu *UserSettingsUpdate) SetNillableLanguage(u *usersettings.Language) *UserSettingsUpdate {
	if u != nil {
		usu.SetLanguage(*u)
	}
	return usu
}

// SetSendingFrequency sets the sending_frequency field.
func (usu *UserSettingsUpdate) SetSendingFrequency(uf usersettings.SendingFrequency) *UserSettingsUpdate {
	usu.mutation.SetSendingFrequency(uf)
	return usu
}

// SetNillableSendingFrequency sets the sending_frequency field if the given value is not nil.
func (usu *UserSettingsUpdate) SetNillableSendingFrequency(uf *usersettings.SendingFrequency) *UserSettingsUpdate {
	if uf != nil {
		usu.SetSendingFrequency(*uf)
	}
	return usu
}

// SetLastSending sets the last_sending field.
func (usu *UserSettingsUpdate) SetLastSending(t time.Time) *UserSettingsUpdate {
	usu.mutation.SetLastSending(t)
	return usu
}

// SetNillableLastSending sets the last_sending field if the given value is not nil.
func (usu *UserSettingsUpdate) SetNillableLastSending(t *time.Time) *UserSettingsUpdate {
	if t != nil {
		usu.SetLastSending(*t)
	}
	return usu
}

// ClearLastSending clears the value of last_sending.
func (usu *UserSettingsUpdate) ClearLastSending() *UserSettingsUpdate {
	usu.mutation.ClearLastSending()
	return usu
}

// SetUserID sets the user edge to User by id.
func (usu *UserSettingsUpdate) SetUserID(id int) *UserSettingsUpdate {
	usu.mutation.SetUserID(id)
	return usu
}

// SetUser sets the user edge to User.
func (usu *UserSettingsUpdate) SetUser(u *User) *UserSettingsUpdate {
	return usu.SetUserID(u.ID)
}

// ClearUser clears the user edge to User.
func (usu *UserSettingsUpdate) ClearUser() *UserSettingsUpdate {
	usu.mutation.ClearUser()
	return usu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (usu *UserSettingsUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := usu.mutation.Language(); ok {
		if err := usersettings.LanguageValidator(v); err != nil {
			return 0, fmt.Errorf("ent: validator failed for field \"language\": %v", err)
		}
	}
	if v, ok := usu.mutation.SendingFrequency(); ok {
		if err := usersettings.SendingFrequencyValidator(v); err != nil {
			return 0, fmt.Errorf("ent: validator failed for field \"sending_frequency\": %v", err)
		}
	}

	if _, ok := usu.mutation.UserID(); usu.mutation.UserCleared() && !ok {
		return 0, errors.New("ent: clearing a unique edge \"user\"")
	}
	var (
		err      error
		affected int
	)
	if len(usu.hooks) == 0 {
		affected, err = usu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserSettingsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			usu.mutation = mutation
			affected, err = usu.sqlSave(ctx)
			return affected, err
		})
		for i := len(usu.hooks) - 1; i >= 0; i-- {
			mut = usu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, usu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (usu *UserSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := usu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (usu *UserSettingsUpdate) Exec(ctx context.Context) error {
	_, err := usu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usu *UserSettingsUpdate) ExecX(ctx context.Context) {
	if err := usu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (usu *UserSettingsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usersettings.Table,
			Columns: usersettings.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usersettings.FieldID,
			},
		},
	}
	if ps := usu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usu.mutation.UrgentWords(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: usersettings.FieldUrgentWords,
		})
	}
	if usu.mutation.UrgentWordsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: usersettings.FieldUrgentWords,
		})
	}
	if value, ok := usu.mutation.BannedWords(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: usersettings.FieldBannedWords,
		})
	}
	if usu.mutation.BannedWordsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: usersettings.FieldBannedWords,
		})
	}
	if value, ok := usu.mutation.Language(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: usersettings.FieldLanguage,
		})
	}
	if value, ok := usu.mutation.SendingFrequency(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: usersettings.FieldSendingFrequency,
		})
	}
	if value, ok := usu.mutation.LastSending(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: usersettings.FieldLastSending,
		})
	}
	if usu.mutation.LastSendingCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: usersettings.FieldLastSending,
		})
	}
	if usu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usersettings.UserTable,
			Columns: []string{usersettings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usersettings.UserTable,
			Columns: []string{usersettings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, usu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersettings.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// UserSettingsUpdateOne is the builder for updating a single UserSettings entity.
type UserSettingsUpdateOne struct {
	config
	hooks    []Hook
	mutation *UserSettingsMutation
}

// SetUrgentWords sets the urgent_words field.
func (usuo *UserSettingsUpdateOne) SetUrgentWords(s []string) *UserSettingsUpdateOne {
	usuo.mutation.SetUrgentWords(s)
	return usuo
}

// ClearUrgentWords clears the value of urgent_words.
func (usuo *UserSettingsUpdateOne) ClearUrgentWords() *UserSettingsUpdateOne {
	usuo.mutation.ClearUrgentWords()
	return usuo
}

// SetBannedWords sets the banned_words field.
func (usuo *UserSettingsUpdateOne) SetBannedWords(s []string) *UserSettingsUpdateOne {
	usuo.mutation.SetBannedWords(s)
	return usuo
}

// ClearBannedWords clears the value of banned_words.
func (usuo *UserSettingsUpdateOne) ClearBannedWords() *UserSettingsUpdateOne {
	usuo.mutation.ClearBannedWords()
	return usuo
}

// SetLanguage sets the language field.
func (usuo *UserSettingsUpdateOne) SetLanguage(u usersettings.Language) *UserSettingsUpdateOne {
	usuo.mutation.SetLanguage(u)
	return usuo
}

// SetNillableLanguage sets the language field if the given value is not nil.
func (usuo *UserSettingsUpdateOne) SetNillableLanguage(u *usersettings.Language) *UserSettingsUpdateOne {
	if u != nil {
		usuo.SetLanguage(*u)
	}
	return usuo
}

// SetSendingFrequency sets the sending_frequency field.
func (usuo *UserSettingsUpdateOne) SetSendingFrequency(uf usersettings.SendingFrequency) *UserSettingsUpdateOne {
	usuo.mutation.SetSendingFrequency(uf)
	return usuo
}

// SetNillableSendingFrequency sets the sending_frequency field if the given value is not nil.
func (usuo *UserSettingsUpdateOne) SetNillableSendingFrequency(uf *usersettings.SendingFrequency) *UserSettingsUpdateOne {
	if uf != nil {
		usuo.SetSendingFrequency(*uf)
	}
	return usuo
}

// SetLastSending sets the last_sending field.
func (usuo *UserSettingsUpdateOne) SetLastSending(t time.Time) *UserSettingsUpdateOne {
	usuo.mutation.SetLastSending(t)
	return usuo
}

// SetNillableLastSending sets the last_sending field if the given value is not nil.
func (usuo *UserSettingsUpdateOne) SetNillableLastSending(t *time.Time) *UserSettingsUpdateOne {
	if t != nil {
		usuo.SetLastSending(*t)
	}
	return usuo
}

// ClearLastSending clears the value of last_sending.
func (usuo *UserSettingsUpdateOne) ClearLastSending() *UserSettingsUpdateOne {
	usuo.mutation.ClearLastSending()
	return usuo
}

// SetUserID sets the user edge to User by id.
func (usuo *UserSettingsUpdateOne) SetUserID(id int) *UserSettingsUpdateOne {
	usuo.mutation.SetUserID(id)
	return usuo
}

// SetUser sets the user edge to User.
func (usuo *UserSettingsUpdateOne) SetUser(u *User) *UserSettingsUpdateOne {
	return usuo.SetUserID(u.ID)
}

// ClearUser clears the user edge to User.
func (usuo *UserSettingsUpdateOne) ClearUser() *UserSettingsUpdateOne {
	usuo.mutation.ClearUser()
	return usuo
}

// Save executes the query and returns the updated entity.
func (usuo *UserSettingsUpdateOne) Save(ctx context.Context) (*UserSettings, error) {
	if v, ok := usuo.mutation.Language(); ok {
		if err := usersettings.LanguageValidator(v); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"language\": %v", err)
		}
	}
	if v, ok := usuo.mutation.SendingFrequency(); ok {
		if err := usersettings.SendingFrequencyValidator(v); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"sending_frequency\": %v", err)
		}
	}

	if _, ok := usuo.mutation.UserID(); usuo.mutation.UserCleared() && !ok {
		return nil, errors.New("ent: clearing a unique edge \"user\"")
	}
	var (
		err  error
		node *UserSettings
	)
	if len(usuo.hooks) == 0 {
		node, err = usuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserSettingsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			usuo.mutation = mutation
			node, err = usuo.sqlSave(ctx)
			return node, err
		})
		for i := len(usuo.hooks) - 1; i >= 0; i-- {
			mut = usuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, usuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (usuo *UserSettingsUpdateOne) SaveX(ctx context.Context) *UserSettings {
	us, err := usuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return us
}

// Exec executes the query on the entity.
func (usuo *UserSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := usuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usuo *UserSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := usuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (usuo *UserSettingsUpdateOne) sqlSave(ctx context.Context) (us *UserSettings, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usersettings.Table,
			Columns: usersettings.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usersettings.FieldID,
			},
		},
	}
	id, ok := usuo.mutation.ID()
	if !ok {
		return nil, fmt.Errorf("missing UserSettings.ID for update")
	}
	_spec.Node.ID.Value = id
	if value, ok := usuo.mutation.UrgentWords(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: usersettings.FieldUrgentWords,
		})
	}
	if usuo.mutation.UrgentWordsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: usersettings.FieldUrgentWords,
		})
	}
	if value, ok := usuo.mutation.BannedWords(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: usersettings.FieldBannedWords,
		})
	}
	if usuo.mutation.BannedWordsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: usersettings.FieldBannedWords,
		})
	}
	if value, ok := usuo.mutation.Language(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: usersettings.FieldLanguage,
		})
	}
	if value, ok := usuo.mutation.SendingFrequency(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: usersettings.FieldSendingFrequency,
		})
	}
	if value, ok := usuo.mutation.LastSending(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: usersettings.FieldLastSending,
		})
	}
	if usuo.mutation.LastSendingCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: usersettings.FieldLastSending,
		})
	}
	if usuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usersettings.UserTable,
			Columns: []string{usersettings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usersettings.UserTable,
			Columns: []string{usersettings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	us = &UserSettings{config: usuo.config}
	_spec.Assign = us.assignValues
	_spec.ScanValues = us.scanValues()
	if err = sqlgraph.UpdateNode(ctx, usuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersettings.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return us, nil
}
