// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/ErrorBoi/feedparserbot/ent/predicate"
	"github.com/ErrorBoi/feedparserbot/ent/usersettings"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// UserSettingsDelete is the builder for deleting a UserSettings entity.
type UserSettingsDelete struct {
	config
	hooks      []Hook
	mutation   *UserSettingsMutation
	predicates []predicate.UserSettings
}

// Where adds a new predicate to the delete builder.
func (usd *UserSettingsDelete) Where(ps ...predicate.UserSettings) *UserSettingsDelete {
	usd.predicates = append(usd.predicates, ps...)
	return usd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (usd *UserSettingsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(usd.hooks) == 0 {
		affected, err = usd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserSettingsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			usd.mutation = mutation
			affected, err = usd.sqlExec(ctx)
			return affected, err
		})
		for i := len(usd.hooks) - 1; i >= 0; i-- {
			mut = usd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, usd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (usd *UserSettingsDelete) ExecX(ctx context.Context) int {
	n, err := usd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (usd *UserSettingsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: usersettings.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usersettings.FieldID,
			},
		},
	}
	if ps := usd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, usd.driver, _spec)
}

// UserSettingsDeleteOne is the builder for deleting a single UserSettings entity.
type UserSettingsDeleteOne struct {
	usd *UserSettingsDelete
}

// Exec executes the deletion query.
func (usdo *UserSettingsDeleteOne) Exec(ctx context.Context) error {
	n, err := usdo.usd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usersettings.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (usdo *UserSettingsDeleteOne) ExecX(ctx context.Context) {
	usdo.usd.ExecX(ctx)
}
