// Code generated by entc, DO NOT EDIT.

package usersettings

import (
	"time"

	"github.com/ErrorBoi/feedparserbot/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// LastSending applies equality check predicate on the "last_sending" field. It's identical to LastSendingEQ.
func LastSending(v time.Time) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLastSending), v))
	})
}

// UrgentWordsIsNil applies the IsNil predicate on the "urgent_words" field.
func UrgentWordsIsNil() predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldUrgentWords)))
	})
}

// UrgentWordsNotNil applies the NotNil predicate on the "urgent_words" field.
func UrgentWordsNotNil() predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldUrgentWords)))
	})
}

// BannedWordsIsNil applies the IsNil predicate on the "banned_words" field.
func BannedWordsIsNil() predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldBannedWords)))
	})
}

// BannedWordsNotNil applies the NotNil predicate on the "banned_words" field.
func BannedWordsNotNil() predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldBannedWords)))
	})
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v Language) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLanguage), v))
	})
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v Language) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLanguage), v))
	})
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...Language) predicate.UserSettings {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserSettings(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLanguage), v...))
	})
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...Language) predicate.UserSettings {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserSettings(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLanguage), v...))
	})
}

// SendingFrequencyEQ applies the EQ predicate on the "sending_frequency" field.
func SendingFrequencyEQ(v SendingFrequency) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSendingFrequency), v))
	})
}

// SendingFrequencyNEQ applies the NEQ predicate on the "sending_frequency" field.
func SendingFrequencyNEQ(v SendingFrequency) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSendingFrequency), v))
	})
}

// SendingFrequencyIn applies the In predicate on the "sending_frequency" field.
func SendingFrequencyIn(vs ...SendingFrequency) predicate.UserSettings {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserSettings(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSendingFrequency), v...))
	})
}

// SendingFrequencyNotIn applies the NotIn predicate on the "sending_frequency" field.
func SendingFrequencyNotIn(vs ...SendingFrequency) predicate.UserSettings {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserSettings(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSendingFrequency), v...))
	})
}

// LastSendingEQ applies the EQ predicate on the "last_sending" field.
func LastSendingEQ(v time.Time) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLastSending), v))
	})
}

// LastSendingNEQ applies the NEQ predicate on the "last_sending" field.
func LastSendingNEQ(v time.Time) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLastSending), v))
	})
}

// LastSendingIn applies the In predicate on the "last_sending" field.
func LastSendingIn(vs ...time.Time) predicate.UserSettings {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserSettings(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLastSending), v...))
	})
}

// LastSendingNotIn applies the NotIn predicate on the "last_sending" field.
func LastSendingNotIn(vs ...time.Time) predicate.UserSettings {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserSettings(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLastSending), v...))
	})
}

// LastSendingGT applies the GT predicate on the "last_sending" field.
func LastSendingGT(v time.Time) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLastSending), v))
	})
}

// LastSendingGTE applies the GTE predicate on the "last_sending" field.
func LastSendingGTE(v time.Time) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLastSending), v))
	})
}

// LastSendingLT applies the LT predicate on the "last_sending" field.
func LastSendingLT(v time.Time) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLastSending), v))
	})
}

// LastSendingLTE applies the LTE predicate on the "last_sending" field.
func LastSendingLTE(v time.Time) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLastSending), v))
	})
}

// LastSendingIsNil applies the IsNil predicate on the "last_sending" field.
func LastSendingIsNil() predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldLastSending)))
	})
}

// LastSendingNotNil applies the NotNil predicate on the "last_sending" field.
func LastSendingNotNil() predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldLastSending)))
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.UserSettings) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.UserSettings) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserSettings) predicate.UserSettings {
	return predicate.UserSettings(func(s *sql.Selector) {
		p(s.Not())
	})
}
