// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
